---
- hosts: all
  become: true
  pre_tasks:

  - name: Update Repo Index
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false

- hosts: webdb_server
  become: true
  tasks:

  - name: Glance Install
    apt:
      name:
        - glance
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Keystone Install
    apt:
      name:
        - keystone
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Nova Install
    apt:
      name:
        - nova-compute
      state: latest
    when: ansible_distribution == "Ubuntu"
